### ISSUE TITLE
Error: package or namespace load failed for ‘STexampleData’:

### ISSUE THREAD

**Issue by ghost** [lmweber/STexampleData#4]
Hi This is the error i receive when I load the package, is anyone familiar with this? 
```r
Error: package or namespace load failed for ‘STexampleData’:
 .onLoad failed in loadNamespace() for 'STexampleData', details:
  call: (function (cond)
  error: error in evaluating the argument 'x' in selecting a method for function 'query': Failed to collect lazy table.
Caused by error in `db_collect()`:
! Arguments in `...` must be used.
✖ Problematic argument:
• ..1 = Inf
ℹ Did you misspell an argument name?
```

**Comment by lmweber** [comment]
Hi, apologies for the delay. Is this problem resolved?

I haven't seen this error before, but it looks like it may be related to a problem in your R session or installed libraries. You could try re-starting R and/or your computer, and alternatively try re-installing R and the `STexampleData` package.

**Comment by ghost** [comment]
yes, no worries, i think it was because of the package dpylr. 
This fixed it devtools::install_version("dbplyr", version = "2.3.4")

**Comment by lmweber** [comment]
Ok great, thanks for letting me know!
